apiVersion: v1
kind: Service
metadata:
  name: prometheus-internal-lb
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: monitoring-kube-prometheus-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP